// <auto-generated />
using System;
using CalisthenicsSkillTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalisthenicsSkillTracker.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260122183000_SeedInitialEntities")]
    partial class SeedInitialEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalisthenicsSkillTracker.Models.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MeasurementType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SkillType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("82bb355d-d50d-472c-8ac4-0f6dc3c86cb2"),
                            Category = 1,
                            Description = "A static hold balancing on hands with body parallel to ground",
                            MeasurementType = 3,
                            Name = "Planche",
                            SkillType = 1
                        },
                        new
                        {
                            Id = new Guid("dcf2edd8-602f-4b96-8521-57b34c5ece9f"),
                            Category = 2,
                            Description = "Balance on hands, can be against a wall or freestanding",
                            MeasurementType = 3,
                            Name = "Handstand",
                            SkillType = 1
                        },
                        new
                        {
                            Id = new Guid("9aa10e18-49f5-4b90-8613-74eec06259c0"),
                            Category = 1,
                            Description = "Pull body up on a bar until chin passes the bar",
                            MeasurementType = 2,
                            Name = "Pull-Up",
                            SkillType = 2
                        },
                        new
                        {
                            Id = new Guid("f28ed423-4cb0-4451-90a5-2cf63723ad32"),
                            Category = 1,
                            Description = "Pull up and push over a bar in one smooth motion",
                            MeasurementType = 2,
                            Name = "Muscle-Up",
                            SkillType = 2
                        },
                        new
                        {
                            Id = new Guid("ff8ad0b0-6b1a-47d5-b2d5-a6df0e59b54c"),
                            Category = 1,
                            Description = "Hold body horizontal while hanging from a bar",
                            MeasurementType = 3,
                            Name = "Front Lever",
                            SkillType = 2
                        });
                });

            modelBuilder.Entity("CalisthenicsSkillTracker.Models.SkillProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("Progression")
                        .HasColumnType("int");

                    b.Property<int?>("Repetitions")
                        .HasColumnType("int");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("SkillProgressRecords");

                    b.HasData(
                        new
                        {
                            Id = new Guid("29eedd24-2050-4d7c-88d9-58982580bbfb"),
                            Date = new DateTime(2026, 1, 17, 18, 30, 0, 39, DateTimeKind.Utc).AddTicks(8351),
                            Duration = 30,
                            Notes = "Good form, need more wrist strength",
                            Progression = 1,
                            SkillId = new Guid("82bb355d-d50d-472c-8ac4-0f6dc3c86cb2"),
                            UserId = new Guid("e70607c0-c065-43ce-b602-15b689784194")
                        },
                        new
                        {
                            Id = new Guid("0f28d0e8-06a8-4303-b355-7e3100c12981"),
                            Date = new DateTime(2026, 1, 19, 18, 30, 0, 39, DateTimeKind.Utc).AddTicks(8363),
                            Notes = "Felt strong today",
                            Repetitions = 10,
                            SkillId = new Guid("9aa10e18-49f5-4b90-8613-74eec06259c0"),
                            UserId = new Guid("776ada73-4ef6-4c12-8934-1e79dbb5e03e")
                        },
                        new
                        {
                            Id = new Guid("c9d51133-fa50-4904-b0cf-18fa9efe8429"),
                            Date = new DateTime(2026, 1, 20, 18, 30, 0, 39, DateTimeKind.Utc).AddTicks(8367),
                            Repetitions = 3,
                            SkillId = new Guid("f28ed423-4cb0-4451-90a5-2cf63723ad32"),
                            UserId = new Guid("91fca50a-7cdd-430f-b08c-dbdaa597ba26")
                        },
                        new
                        {
                            Id = new Guid("1811c055-dd54-482d-ad03-7f160059749f"),
                            Date = new DateTime(2026, 1, 21, 18, 30, 0, 39, DateTimeKind.Utc).AddTicks(8371),
                            Duration = 20,
                            SkillId = new Guid("dcf2edd8-602f-4b96-8521-57b34c5ece9f"),
                            UserId = new Guid("82042202-ba9c-44f5-86fb-4b191dbf966c")
                        },
                        new
                        {
                            Id = new Guid("743342d2-1d00-4168-b135-753d62d07127"),
                            Date = new DateTime(2026, 1, 22, 18, 30, 0, 39, DateTimeKind.Utc).AddTicks(8373),
                            Duration = 10,
                            Notes = "Core tight, need to extend legs fully",
                            SkillId = new Guid("ff8ad0b0-6b1a-47d5-b2d5-a6df0e59b54c"),
                            UserId = new Guid("c7cebde1-1c04-4bff-a388-d42961e5ece7")
                        });
                });

            modelBuilder.Entity("CalisthenicsSkillTracker.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("LastName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c7cebde1-1c04-4bff-a388-d42961e5ece7"),
                            CreatedAt = new DateTime(2026, 1, 22, 18, 30, 0, 39, DateTimeKind.Utc).AddTicks(9199),
                            Email = "alex.petrov@example.com",
                            FirstName = "Alex",
                            LastName = "Petrov",
                            PasswordHash = "Pass123!",
                            Username = "athlete01"
                        },
                        new
                        {
                            Id = new Guid("82042202-ba9c-44f5-86fb-4b191dbf966c"),
                            CreatedAt = new DateTime(2026, 1, 22, 18, 30, 0, 39, DateTimeKind.Utc).AddTicks(9202),
                            Email = "maria.ivanova@example.com",
                            FirstName = "Maria",
                            LastName = "Ivanova",
                            PasswordHash = "Fit2026!",
                            Username = "fitgirl92"
                        },
                        new
                        {
                            Id = new Guid("91fca50a-7cdd-430f-b08c-dbdaa597ba26"),
                            CreatedAt = new DateTime(2026, 1, 22, 18, 30, 0, 39, DateTimeKind.Utc).AddTicks(9203),
                            Email = "daniel.georgiev@example.com",
                            FirstName = "Daniel",
                            LastName = "Georgiev",
                            PasswordHash = "GytTime1!",
                            Username = "gymking"
                        },
                        new
                        {
                            Id = new Guid("776ada73-4ef6-4c12-8934-1e79dbb5e03e"),
                            CreatedAt = new DateTime(2026, 1, 22, 18, 30, 0, 39, DateTimeKind.Utc).AddTicks(9204),
                            Email = "elena.dimitrova@example.com",
                            FirstName = "Elena",
                            LastName = "Dimitrova",
                            PasswordHash = "Calis2026!",
                            Username = "calisthenics_pro"
                        },
                        new
                        {
                            Id = new Guid("e70607c0-c065-43ce-b602-15b689784194"),
                            CreatedAt = new DateTime(2026, 1, 22, 18, 30, 0, 39, DateTimeKind.Utc).AddTicks(9206),
                            Email = "ivan.kostov@example.com",
                            FirstName = "Ivan",
                            LastName = "Kostov",
                            PasswordHash = "StrongMuscle1!",
                            Username = "muscle_man"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CalisthenicsSkillTracker.Models.SkillProgress", b =>
                {
                    b.HasOne("CalisthenicsSkillTracker.Models.Skill", "Skill")
                        .WithMany("SkillProgressRecords")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalisthenicsSkillTracker.Models.User", "PerformedBy")
                        .WithMany("SkillProgressRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerformedBy");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CalisthenicsSkillTracker.Models.Skill", b =>
                {
                    b.Navigation("SkillProgressRecords");
                });

            modelBuilder.Entity("CalisthenicsSkillTracker.Models.User", b =>
                {
                    b.Navigation("SkillProgressRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
