// <auto-generated />
using System;
using CalisthenicsSkillTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalisthenicsSkillTracker.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260406200301_SeedExercisesAndSkills")]
    partial class SeedExercisesAndSkills
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalisthenicsSkillTracker.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CalisthenicsSkillTracker.Data.Models.ApplicationUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("CalisthenicsSkillTracker.Data.Models.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseType")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MeasurementType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111111"),
                            Category = 1,
                            Description = "A beginner-friendly pushing exercise that builds pressing strength.",
                            Difficulty = 1,
                            ExerciseType = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1609858922128-d24e042be1f1?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            MeasurementType = 1,
                            Name = "Incline Push Up"
                        },
                        new
                        {
                            Id = new Guid("c2222222-2222-2222-2222-222222222222"),
                            Category = 1,
                            Description = "A fundamental bodyweight pushing exercise for chest, shoulders, and triceps.",
                            Difficulty = 1,
                            ExerciseType = 1,
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1666956838404-02f23fa07123?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            MeasurementType = 1,
                            Name = "Standard Push Up"
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333333"),
                            Category = 1,
                            Description = "A vertical pushing exercise that prepares the body for handstand work.",
                            Difficulty = 2,
                            ExerciseType = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1599744331048-d58b430fb098?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZGVjbGluZSUyMHB1c2glMjB1cHxlbnwwfHwwfHx8MA%3D%3D",
                            MeasurementType = 1,
                            Name = "Pike Push Up"
                        },
                        new
                        {
                            Id = new Guid("c4444444-4444-4444-4444-444444444444"),
                            Category = 1,
                            Description = "A horizontal pulling exercise that develops upper back strength.",
                            Difficulty = 1,
                            ExerciseType = 2,
                            ImageUrl = "https://www.kettlebellkings.com/cdn/shop/articles/Inverted-Row.jpg?v=1703750562",
                            MeasurementType = 1,
                            Name = "Bodyweight Row"
                        },
                        new
                        {
                            Id = new Guid("c5555555-5555-5555-5555-555555555555"),
                            Category = 1,
                            Description = "A classic vertical pulling exercise that builds serious upper body strength.",
                            Difficulty = 2,
                            ExerciseType = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80",
                            MeasurementType = 1,
                            Name = "Pull Up"
                        },
                        new
                        {
                            Id = new Guid("c6666666-6666-6666-6666-666666666666"),
                            Category = 1,
                            Description = "A compound pushing exercise for chest, shoulders, and triceps.",
                            Difficulty = 2,
                            ExerciseType = 1,
                            ImageUrl = "https://training.fit/wp-content/uploads/2020/02/dips.png",
                            MeasurementType = 1,
                            Name = "Dip"
                        },
                        new
                        {
                            Id = new Guid("c7777777-7777-7777-7777-777777777777"),
                            Category = 1,
                            Description = "A core exercise that improves abdominal strength and compression.",
                            Difficulty = 1,
                            ExerciseType = 3,
                            ImageUrl = "https://images.unsplash.com/photo-1517963879433-6ad2b056d712?auto=format&fit=crop&w=1200&q=80",
                            MeasurementType = 1,
                            Name = "Hanging Knee Raise"
                        },
                        new
                        {
                            Id = new Guid("c8888888-8888-8888-8888-888888888888"),
                            Category = 1,
                            Description = "A static core hold that builds compression and shoulder stability.",
                            Difficulty = 2,
                            ExerciseType = 3,
                            ImageUrl = "https://gravity.fitness/cdn/shop/articles/male-athlete-doing-l-sit-exercise-on-bricks-2021-08-27-19-27-31-utc.jpg?v=1651655207",
                            MeasurementType = 2,
                            Name = "L-Sit Hold"
                        },
                        new
                        {
                            Id = new Guid("c9999999-9999-9999-9999-999999999999"),
                            Category = 2,
                            Description = "A static inverted hold focused on balance and shoulder endurance.",
                            Difficulty = 3,
                            ExerciseType = 1,
                            ImageUrl = "https://cdn.yogajournal.com/wp-content/uploads/2021/11/Handstand_Andrew-Clark.jpg",
                            MeasurementType = 2,
                            Name = "Handstand Hold"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Category = 1,
                            Description = "A unilateral lower body exercise requiring balance, mobility, and strength.",
                            Difficulty = 3,
                            ExerciseType = 4,
                            ImageUrl = "https://hips.hearstapps.com/hmg-prod/images/pistol-squat-regular-pistol-squat-233-1654102650.jpg?crop=0.560xw:0.839xh;0.209xw,0.161xh&resize=640:*",
                            MeasurementType = 1,
                            Name = "Pistol Squat"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Category = 1,
                            Description = "A scaled front lever exercise emphasizing body tension and pulling strength.",
                            Difficulty = 3,
                            ExerciseType = 2,
                            ImageUrl = "https://workout-temple.com/wp-content/uploads/2022/11/sideview-tucked-front-lever.jpg",
                            MeasurementType = 2,
                            Name = "Front Lever Tuck Hold"
                        });
                });

            modelBuilder.Entity("CalisthenicsSkillTracker.Data.Models.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MeasurementType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SkillType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Category = 1,
                            Description = "A foundational pushing skill that builds upper body strength and control.",
                            Difficulty = 1,
                            ImageUrl = "https://www.sixstarpro.com/cdn/shop/articles/how-to-get-better-at-push-ups_c96cd61d-63d8-4bd0-a93e-e3a8dee52408.jpg?v=1726000547",
                            MeasurementType = 1,
                            Name = "Push Up",
                            SkillType = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Category = 1,
                            Description = "A classic pulling skill that develops back, arm, and grip strength.",
                            Difficulty = 2,
                            ImageUrl = "https://velocitywestchester.com/wp-content/uploads/2025/06/rsw_1280-9.webp",
                            MeasurementType = 1,
                            Name = "Pull Up",
                            SkillType = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Category = 1,
                            Description = "A compound pushing skill focused on chest, shoulders, and triceps.",
                            Difficulty = 2,
                            ImageUrl = "https://training.fit/wp-content/uploads/2020/02/dips.png",
                            MeasurementType = 1,
                            Name = "Dip",
                            SkillType = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Category = 1,
                            Description = "A static core skill requiring hip flexor and abdominal strength.",
                            Difficulty = 2,
                            ImageUrl = "https://gravity.fitness/cdn/shop/articles/male-athlete-doing-l-sit-exercise-on-bricks-2021-08-27-19-27-31-utc.jpg?v=1651655207",
                            MeasurementType = 2,
                            Name = "L-Sit",
                            SkillType = 3
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Category = 2,
                            Description = "An inverted balance skill that develops body awareness and shoulder stability.",
                            Difficulty = 3,
                            ImageUrl = "https://cdn.yogajournal.com/wp-content/uploads/2021/11/Handstand_Andrew-Clark.jpg",
                            MeasurementType = 2,
                            Name = "Handstand",
                            SkillType = 1
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Category = 1,
                            Description = "A demanding static pulling skill requiring full-body tension.",
                            Difficulty = 4,
                            ImageUrl = "https://caliathletics.com/wp-content/uploads/2018/09/Frontback-lever.jpg",
                            MeasurementType = 2,
                            Name = "Front Lever",
                            SkillType = 2
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Category = 1,
                            Description = "A static hold that challenges shoulder mobility and pulling strength.",
                            Difficulty = 4,
                            ImageUrl = "https://cdn.shopify.com/s/files/1/0568/6280/2107/files/back_lever_1a0f7520-1b68-426f-91a2-7c192a81df24_480x480.jpg",
                            MeasurementType = 2,
                            Name = "Back Lever",
                            SkillType = 2
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Category = 1,
                            Description = "An elite pushing skill performed with the body held parallel to the ground.",
                            Difficulty = 4,
                            ImageUrl = "https://andrystrong.com/wp-content/uploads/2023/10/bas-1024x576.webp",
                            MeasurementType = 2,
                            Name = "Planche",
                            SkillType = 1
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Category = 1,
                            Description = "A single-leg lower body skill demanding strength, balance, and mobility.",
                            Difficulty = 3,
                            ImageUrl = "https://hips.hearstapps.com/hmg-prod/images/pistol-squat-regular-pistol-squat-233-1654102650.jpg?crop=0.560xw:0.839xh;0.209xw,0.161xh&resize=640:*",
                            MeasurementType = 1,
                            Name = "Pistol Squat",
                            SkillType = 4
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Category = 1,
                            Description = "A powerful core skill emphasizing anti-extension strength and control.",
                            Difficulty = 3,
                            ImageUrl = "https://cdn.shopify.com/s/files/1/0568/6280/2107/files/dragon_flag_600x600.jpg",
                            MeasurementType = 1,
                            Name = "Dragon Flag",
                            SkillType = 3
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Category = 5,
                            Description = "An advanced static skill combining lateral core strength and pulling power.",
                            Difficulty = 4,
                            ImageUrl = "https://www.streetworkoutstkilda.com/wp-content/uploads/2020/08/human-flag-beast-1.jpeg",
                            MeasurementType = 2,
                            Name = "Human Flag",
                            SkillType = 3
                        });
                });

            modelBuilder.Entity("CalisthenicsSkillTracker.Data.Models.SkillProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Progression")
                        .HasColumnType("int");

                    b.Property<int?>("Repetitions")
                        .HasColumnType("int");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("SkillProgressRecords");
                });

            modelBuilder.Entity("CalisthenicsSkillTracker.Data.Models.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("End")
                        .HasColumnType("time");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan>("Start")
                        .HasColumnType("time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("CalisthenicsSkillTracker.Data.Models.WorkoutExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutExercises");
                });

            modelBuilder.Entity("CalisthenicsSkillTracker.Data.Models.WorkoutSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Progression")
                        .HasColumnType("int");

                    b.Property<int?>("Repetitions")
                        .HasColumnType("int");

                    b.Property<int>("SetNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkoutExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutExerciseId");

                    b.ToTable("WorkoutSets");
                });

            modelBuilder.Entity("ExerciseSkills", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ExerciseId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("ExerciseSkills");

                    b.HasData(
                        new
                        {
                            ExerciseId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            SkillId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ExerciseId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            SkillId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ExerciseId = new Guid("c3333333-3333-3333-3333-333333333333"),
                            SkillId = new Guid("55555555-5555-5555-5555-555555555555")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UserFavoriteExercises", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("UserFavoriteExercises");
                });

            modelBuilder.Entity("UserFavoriteSkills", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("UserFavoriteSkills");
                });

            modelBuilder.Entity("CalisthenicsSkillTracker.Data.Models.ApplicationUserRole", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalisthenicsSkillTracker.Data.Models.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalisthenicsSkillTracker.Data.Models.SkillProgress", b =>
                {
                    b.HasOne("CalisthenicsSkillTracker.Data.Models.Skill", "Skill")
                        .WithMany("SkillProgressRecords")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalisthenicsSkillTracker.Data.Models.ApplicationUser", "PerformedBy")
                        .WithMany("SkillProgressRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerformedBy");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("CalisthenicsSkillTracker.Data.Models.Workout", b =>
                {
                    b.HasOne("CalisthenicsSkillTracker.Data.Models.ApplicationUser", "User")
                        .WithMany("Workouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalisthenicsSkillTracker.Data.Models.WorkoutExercise", b =>
                {
                    b.HasOne("CalisthenicsSkillTracker.Data.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalisthenicsSkillTracker.Data.Models.Workout", "Workout")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("CalisthenicsSkillTracker.Data.Models.WorkoutSet", b =>
                {
                    b.HasOne("CalisthenicsSkillTracker.Data.Models.WorkoutExercise", "WorkoutExercise")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutExercise");
                });

            modelBuilder.Entity("ExerciseSkills", b =>
                {
                    b.HasOne("CalisthenicsSkillTracker.Data.Models.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalisthenicsSkillTracker.Data.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CalisthenicsSkillTracker.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CalisthenicsSkillTracker.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CalisthenicsSkillTracker.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserFavoriteExercises", b =>
                {
                    b.HasOne("CalisthenicsSkillTracker.Data.Models.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalisthenicsSkillTracker.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserFavoriteSkills", b =>
                {
                    b.HasOne("CalisthenicsSkillTracker.Data.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalisthenicsSkillTracker.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CalisthenicsSkillTracker.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("SkillProgressRecords");

                    b.Navigation("UserRoles");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("CalisthenicsSkillTracker.Data.Models.Skill", b =>
                {
                    b.Navigation("SkillProgressRecords");
                });

            modelBuilder.Entity("CalisthenicsSkillTracker.Data.Models.Workout", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("CalisthenicsSkillTracker.Data.Models.WorkoutExercise", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
